# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5969baa75efa8c2bd3a2882815ee56761f02b4278a4aa6cf2719f30140abe7b9c4b7a71b4fe49b3e6f6fd30f2c2c98e73e147e8211e339c4e31c2802efda14fe

test:
  secret_key_base: eca49e2b0ed3a1a35fdf6215eccbb393aa4cded22598de6d41d6cb7811d72f8ce8d9f5eade299e49ae4e6679d9cd0f4531025a0174d802b367b8a118cf365218

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
